apiVersion: v1
kind: Service
metadata:
  namespace: ksqldb
  name: ksqldb-cluster
spec:
  selector:
    app: ksqldb-cluster
  ports:
    - protocol: "TCP"
      port: 8088
      targetPort: 8088
  clusterIP: None


---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ksqldb
  name: ksqldb-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ksqldb-cluster
  template:
    metadata:
      labels:
        app: ksqldb-cluster
    spec:
      containers:
      - name: ksqldb-server
        image: confluentinc/ksqldb-server:0.11.0
        ports:
        - containerPort: 8088
        env:
        - name: KSQL_LISTENERS
          value: http://0.0.0.0:8088

        - name: KSQL_KSQL_SERVICE_ID
          value: ksql_service_1_

        - name: KSQL_BOOTSTRAP_SERVERS
          value: my-cluster-kafka-brokers.kafka:9092

        - name: KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE
          value: "true"

        - name: KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE
          value: "true"

        # - name: KSQL_KSQL_QUERIES_FILE
        #   value: /path/in/container/queries.sql 
