CREATE STREAM MOVIE_STREAM (
    id INT,
    name VARCHAR
) WITH (
    KAFKA_TOPIC = 'movie-topic',
    VALUE_FORMAT = 'JSON'
);

CREATE TABLE MOVIE_TABLE (
    id VARCHAR PRIMARY KEY,
    name VARCHAR
) WITH (
    KAFKA_TOPIC = 'movie-topic',
    VALUE_FORMAT = 'JSON'
);


SELECT * FROM MOVIE_STREAM EMIT CHANGES;
SELECT * FROM MOVIE_TABLE EMIT CHANGES;


SELECT * FROM MOVIE_STREAM WHERE id = 1 EMIT CHANGES;
SELECT * FROM MOVIE_TABLE WHERE id = '1' EMIT CHANGES;