apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  namespace: kafka
  name: my-cluster
spec:
  kafka:
    version: 2.5.0
    replicas: 1
    resources:
      requests:
        memory: 384Mi
        cpu: 0.2
      limits:
        memory: 1Gi
        cpu: 0.5
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.5"
    storage:
      type: persistent-claim
      size: 100Gi
  zookeeper:
    replicas: 1
    resources:
      requests:
        memory: 384Mi
        cpu: 0.2
      limits:
        memory: 1Gi
        cpu: 0.5
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}